version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker  # Cần để Docker hoạt động
      - run: docker build -t negan-server .

workflows:
  build:
    jobs:
      - build
