version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout  # Tải code từ GitHub về
      - setup_remote_docker
      - run: docker build -t negan-server .

workflows:
  build:
    jobs:
      - build
